# Generated by Django 3.0.6 on 2020-05-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='rApi/images')),
            ],
        ),
    ]
